### ISSUE TITLE
Retake, Use Photo and Cancel buttons do nothing

### ISSUE THREAD

**Issue by richardfisher** [zhangao0086/DKImagePickerController#312]
When taking a photo using the CustomCameraUI, none of the buttons do anything once a photo has been taken. This causes the app to be stuck in the view after a photo has been taken.

I am using version 3.5.3.

**Comment by zhangao0086** [comment]
Please check the latest develop branch. I think this issue has been resolved :)

**Comment by richardfisher** [comment]
I have checked out the develop branch (now version 3.5.5) and I'm afraid I'm still getting the same issue.

**Comment by zhangao0086** [comment]
Updated. 
Closing this thread. Feel free to re-open if your issue is not solved.
