### ISSUE TITLE
Will not select photo when you take a picture

### ISSUE THREAD

**Issue by Bitcosoftware** [zhangao0086/DKImagePickerController#557]
I am using the current Cocoapod dowload and when I take a picture, it will not select the image and return it.  It just loops until I cancel.  I can select an image from the library but not the Camera.

**Comment by deniszhukov** [comment]
Same issue.
I've tried Example project from the repo and getting the same error when I try to take photo.
The error that I'm getting in the output:
UI API called on a background thread

**Comment by jmilillo** [comment]
Seems like switching to TOCropViewController was a step backwards.   The original CLImageEditor offered more features and just needed to be updated.

**Comment by zhangao0086** [comment]
Hi @Bitcosoftware @deniszhukov Could you check the develop branch? I think it has been fixed.
```
pod 'DKImagePickerController', :git => 'https://github.com/zhangao0086/DKImagePickerController.git', :branch => 'develop'
```

@jmilillo If you prefer to `CLImageEditor` rather than `TOCropViewController`. You can make a custom extension like so:
```swift
open class DKImageExtensionPhotoEditor: DKImageBaseExtension, CLImageEditorDelegate {
    
    open  weak var imageEditor: UIViewController?
    open  var metadata: [AnyHashable : Any]?
    open  var didFinishEditing: ((UIImage, [AnyHashable : Any]?) -> Void)?
        
    override open func perform(with extraInfo: [AnyHashable: Any]) {
        guard let image = extraInfo["image"] as? UIImage
            , let didFinishEditing = extraInfo["didFinishEditing"] as? ((UIImage, [AnyHashable : Any]?) -> Void) else { return }
        
        self.metadata = extraInfo["metadata"] as? [AnyHashable : Any]
        self.didFinishEditing = didFinishEditing
        
        let imageEditor = CLImageEditor(image: image, delegate: self)!
        if let tool = imageEditor.toolInfo.subToolInfo(withToolName: "CLToneCurveTool", recursive: false) {
            tool.available = false
        }
        
        if let tool = imageEditor.toolInfo.subToolInfo(withToolName: "CLStickerTool", recursive: false) {
            tool.available = false
        }
        
        self.imageEditor = imageEditor
        
        let imagePickerController = self.context.imagePickerController
        (imagePickerController?.presentedViewController ?? imagePickerController)?.present(imageEditor, animated: true, completion: nil)
    }

    override open func finish() {
        self.imageEditor?.presentingViewController?.dismiss(animated: true, completion: nil)
    }
    
    // MARK: - CLImageEditorDelegate
    
    open func imageEditor(_ editor: CLImageEditor!, didFinishEditingWith image: UIImage!) {
        if let didFinishEditing = self.didFinishEditing {
            self.metadata?[kCGImagePropertyOrientation as AnyHashable] = NSNumber(integerLiteral: 0)
            
            didFinishEditing(image, self.metadata)
            
            self.didFinishEditing = nil
            self.metadata = nil
        }
    }
    
}
```
than
```swift
DKImageExtensionController.registerExtension(extensionClass: DKImageExtensionPhotoEditor.self, for: DKImageExtensionType.photoEditor)
```

**Comment by deniszhukov** [comment]
@zhangao0086 I've installed pod from git, but unfortunately I'm still experiencing the same issue.

**Comment by zhangao0086** [comment]
@deniszhukov Thanks for your feedback!

In `TOCropViewController 2.4.x`, the signature of the delegate method has been modified. I've made another commit: https://github.com/zhangao0086/DKImagePickerController/commit/3fada261d82af8fc9010c0add6ad67ede0522aab, sorry for that :(

**Comment by deniszhukov** [comment]
@zhangao0086 it works! Even though I'm still getting 
"UI API called on a background thread" when I'm trying to take a picture, but it's not blocking anything.
Thanks

**Comment by zhangao0086** [comment]
Feel free to re-open it if needed :)

**Comment by kaz080** [comment]
Hello @zhangao0086 

> In `TOCropViewController 2.4.x`, the signature of the delegate method has been modified. I've made another commit: [3fada26](https://github.com/zhangao0086/DKImagePickerController/commit/3fada261d82af8fc9010c0add6ad67ede0522aab), sorry for that :(

This change seems the cause of this bug:
https://github.com/TimOliver/TOCropViewController/commit/8eb8ae2561b148e85a79650b8144741c3b8f7eb9
NS_SWIFT_NAME has been removed, maybe that's why the delegate method didn't invoke.

Perhaps it's better to use Swift interface than Obj-C interface.
https://github.com/TimOliver/TOCropViewController#swift-1

**Comment by zhangao0086** [comment]
@kaz080 You're right! The develop branch has been updated https://github.com/zhangao0086/DKImagePickerController/commit/d04cd815a21a4c50162c17d0066e6ad13167a262

**Comment by kaz080** [comment]
@zhangao0086 Wow! Thank you so much!!
