### ISSUE TITLE
Unable to build using Carthage

### ISSUE THREAD

**Issue by jnmackie** [zhangao0086/DKImagePickerController#654]
`command: carthage update --platform ios --no-use-binaries`

I am attempting to install the current version (4.1.7), but have also tried with the version I was previously using (4.0.4) and the Carthage install is failing. I noticed you just updated the library to remove support for iOS 8, and the error when trying to install is pointing to the DKPhotoGallery project

```
CompileSwift normal arm64 (in target 'DKPhotoGallery' from project 'DKPhotoGallery')
    cd /Users/<project path>/Carthage/Checkouts/DKPhotoGallery
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -emit-bc /Users/<project path>/Carthage/Checkouts/DKPhotoGallery/DKPhotoGallery/Preview/D$
/Users/j<project path>/Carthage/Checkouts/DKPhotoGallery/DKPhotoGallery/Preview/DKPhotoBasePreviewVC.swift:38:38: error: 'UIPreviewActionItem' is only available in iOS 9.0 or newer
    func defaultPreviewActions() -> [UIPreviewActionItem]
                                     ^
/Users/<project path>/Carthage/Checkouts/DKPhotoGallery/DKPhotoGallery/Preview/DKPhotoBasePreviewVC.swift:38:10: note: add @available attribute to enclosing instance method
    func defaultPreviewActions() -> [UIPreviewActionItem]
         ^
/Users/<project path>/Carthage/Checkouts/DKPhotoGallery/DKPhotoGallery/Preview/DKPhotoBasePreviewVC.swift:18:17: note: add @available attribute to enclosing protocol
public protocol DKPhotoBasePreviewDataSource : NSObjectProtocol {
                ^
/Users/<project path>/Carthage/Checkouts/DKPhotoGallery/DKPhotoGallery/Preview/DKPhotoBasePreviewVC.swift:97:41: error: 'UIPreviewActionItem' is only available in iOS 9.0 or newer
    private var _customPreviewActions: [UIPreviewActionItem]? {
                                        ^
/Users/<project path>/Carthage/Checkouts/DKPhotoGallery/DKPhotoGallery/Preview/DKPhotoBasePreviewVC.swift:97:17: note: add @available attribute to enclosing property
    private var _customPreviewActions: [UIPreviewActionItem]? {
                ^
/Users/<project path>/Carthage/Checkouts/DKPhotoGallery/DKPhotoGallery/Preview/DKPhotoBasePreviewVC.swift:85:12: note: add @available attribute to enclosing class
open class DKPhotoBasePreviewVC: UIViewController, UIScrollViewDelegate, DKPhotoBasePreviewDataSource {

```

It goes on like that for a little longer, but it looks like the DKPhotoGallery project did not get the same update that the main project did.

I also tried downloading your full project from GitHub and trying to run it by building all of the dependencies locally on my machine, but I get the same error.

**Comment by zhangao0086** [comment]
Sorry for that 😢 Fixed in DKPhotoGallery `0.0.16`.

**Comment by kyounghak** [comment]
i upated it but still have problem with DKPhotoGallery

dyld: Library not loaded: @rpath/SDWebImageFLPlugin.framework/SDWebImageFLPlugin
  Referenced from: /private/var/containers/Bundle/Application/61/test.app/Frameworks/DKPhotoGallery.framework/DKPhotoGallery
  Reason: image not found
(lldb)
